// <auto-generated />
using FranksRestaurant.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FranksRestaurant.Migrations
{
    [DbContext(typeof(FranksDbContext))]
    partial class FranksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FranksRestaurant.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "password",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("FranksRestaurant.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MenuType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 7.99m,
                            Description = "Tequila, lime juice, triple sec",
                            MenuType = 0,
                            Name = "Margarita"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 8.49m,
                            Description = "Whiskey, bitters, sugar, orange peel",
                            MenuType = 0,
                            Name = "Old Fashioned"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 6.99m,
                            Description = "Vodka, tomato juice, spices",
                            MenuType = 0,
                            Name = "Bloody Mary"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 7.49m,
                            Description = "Whiskey, lemon juice, simple syrup",
                            MenuType = 0,
                            Name = "Whiskey Sour"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 8.99m,
                            Description = "Juicy beef burger",
                            MenuType = 1,
                            Name = "Cheeseburger"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 7.99m,
                            Description = "Grilled chicken sandwich",
                            MenuType = 1,
                            Name = "Chicken Sandwich"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 6.99m,
                            Description = "Bacon, Lettuce, and Tomato",
                            MenuType = 1,
                            Name = "BLT Sandwich"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 9.49m,
                            Description = "Crispy fish with taco sauce",
                            MenuType = 1,
                            Name = "Fish Tacos"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 19.99m,
                            Description = "Grilled ribeye with a side",
                            MenuType = 2,
                            Name = "Ribeye Steak"
                        },
                        new
                        {
                            Id = 10,
                            Cost = 13.99m,
                            Description = "Classic spaghetti with meat sauce",
                            MenuType = 2,
                            Name = "Spaghetti Bolognese"
                        },
                        new
                        {
                            Id = 11,
                            Cost = 18.99m,
                            Description = "Grilled salmon served with rice",
                            MenuType = 2,
                            Name = "Salmon Fillet"
                        },
                        new
                        {
                            Id = 12,
                            Cost = 14.99m,
                            Description = "Chicken topped with cheese & marinara",
                            MenuType = 2,
                            Name = "Chicken Parmesan"
                        },
                        new
                        {
                            Id = 13,
                            Cost = 2.99m,
                            Description = "Crispy golden fries",
                            MenuType = 3,
                            Name = "French Fries"
                        },
                        new
                        {
                            Id = 14,
                            Cost = 3.49m,
                            Description = "Crispy battered onion rings",
                            MenuType = 3,
                            Name = "Onion Rings"
                        },
                        new
                        {
                            Id = 15,
                            Cost = 4.99m,
                            Description = "Fresh mixed vegetables with dressing",
                            MenuType = 3,
                            Name = "Garden Salad"
                        },
                        new
                        {
                            Id = 16,
                            Cost = 3.49m,
                            Description = "Creamy mashed potatoes",
                            MenuType = 3,
                            Name = "Mashed Potatoes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
